### ISSUE TITLE
Track fails

### ISSUE THREAD

**Issue by ghost** [kevinelliott/dji#4]
OSX 10.12.1

gem -v
2.0.14.1

dji track -o XXXXXXXXXXXX -p XXXX
/Library/Ruby/Gems/2.0.0/gems/dji-0.7.4/lib/dji/order_tracking.rb:78:in `tracking_details': undefined method `text' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/dji-0.7.4/lib/dji/commands/track/track_command.rb:45:in `track'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/dji-0.7.4/lib/dji/command/base.rb:33:in `perform'
	from /Library/Ruby/Gems/2.0.0/gems/dji-0.7.4/lib/dji/command.rb:31:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/dji-0.7.4/exe/dji:16:in `<top (required)>'
	from /usr/local/bin/dji:23:in `load'
	from /usr/local/bin/dji:23:in `<main>'

fedex works

% dji fedex -c us -p 89074

FedEx Packages for Country us, Postal Code 89074 as of 2016-11-15 17:34:15 -0800
-------------------------------------------------------------------------------------------------------

PACKAGE 1

Origin       : SHENZHEN, CN, CN
Destination  : HENDERSON, NV, US
Tendered     : 2016-11-08 11:41:00 UTC
Picked Up    : 2016-11-08 12:30:00 UTC
Shipped      : 2016-11-09 06:00:00 UTC
Delivered    : 2016-11-10 17:32:00 UTC
Dimensions   : 11x11x5 in.
Total Weight : 4.85 lbs (2.2 kgs)
Status       : Delivered

**Comment by bassrock** [comment]
I am seeing the same issue on ruby 2.3.3

**Comment by kevinelliott** [comment]
Yes, unfortunately DJI broke this some time ago with the introduction of their captcha on the forms. Unfortunately, they have not responded back to my emails about finding an official API to interact with. You might try to contact them as well if you want to help re-enable this.
